<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
	</array>
	<key>name</key>
	<string>LogfilePlus</string>
	<key>scopeName</key>
	<string>text.logfileplus</string>
	<key>uuid</key>
	<string>d633bec3-4194-436d-ac0c-355ecd142422</string>
</dict>
</plist>
